server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healtharchive?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: q1w2e3r4
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:  # 推荐连接池配置
      connection-timeout: 30000
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect   # 关键修改点
        connection.provider_disables_autocommit:  true  # 事务控制增强

  doc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
      display-request-duration: true  # 新增性能监控
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: default
        paths-to-match: /**
        packages-to-scan: com.sudobang.healtharchive


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sudobang.healtharchive.entity   # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true


healtharchive:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: sudobang1234567890abcdefghijklmnopqr
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: pilotwhale1234567890abcdefghijklmnop
    user-ttl: 7200000
    user-token-name: token

# application.yml  示例
pagehelper:
  helper-dialect: mysql  # 数据库方言
  reasonable: true       # 分页合理化
  support-methods-arguments: true
